[tool.ruff]
line-length = 100
exclude = [".venv", ".vectordb", ".data", "__pycache__"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_untyped_defs = false
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = [".venv", ".vectordb", ".data", "__pycache__"]
