[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["data", ".vectordb", ".data"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
